### ISSUE TITLE
tcp and "final"

### ISSUE THREAD

**Issue by joaomilho** [grantila/compd#9]
What exactly is the usage of "final"? When running in any basic docker compose compose that exposes a tcp port it says "Service ... not understood" cause although it finds a match, it is not final 
```ts
if (matches.length === 0 || !matches[matches.length - 1].final) {
```

 If I remove the condition things work great. E.g.

```yaml
#!/usr/bin/env docker-compose -f

version: "3.9"
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
```
